---

version: "{build}"

init:
  - set PATH=C:\ruby%ruby_version%\bin;C:\Program Files\Git\cmd;C:\msys64\usr\bin;C:\msys64\mingw64\bin;C:\Program Files\7-Zip;C:\Program Files\AppVeyor\BuildAgent;C:\Windows\system32
  - if %ruby_version%==2.3.4u (
      appveyor DownloadFile https://dl.bintray.com/msp-greg/ruby_windows/ruby2.3.4u.7z -FileName C:/ruby2.3.4u.7z &
      7z x C:/ruby2.3.4u.7z -oC:/ruby2.3.4u & C:/ruby2.3.4u/ruby2.3.4u_install.cmd)
  - if %ruby_version%==_trunk (
      appveyor DownloadFile https://dl.bintray.com/msp-greg/ruby_windows/ruby_trunk.7z -FileName C:/ruby_trunk.7z &
      7z x C:/ruby_trunk.7z -oC:/ruby_trunk & C:/ruby_trunk/trunk_install.cmd)

install:
  - echo %PATH%

  - ruby --version
  - where ruby

  - gem --version
  - where gem

  - git --version
  - where git

  - bundler --version
  - where bundler

    # see https://github.com/bundler/bundler/issues/5344
  - bundle config force_ruby_platform true
  - bundle install --jobs=3 --retry=3
  - gem list
 
build_script:
  - bundle exec rake clobber
  - bundle exec rake compile

test_script:
  - bundle exec rake test

environment:
  matrix:
    - ruby_version: "2.3.4u"
    - ruby_version: "24-x64"
    - ruby_version: "_trunk"

matrix:
  fast_finish: true
  allow_failures:
    - ruby_version: "_trunk"
